In [68]:
from  typing import Dict, Union, Optional

import pprint

key = Union[int,str]
Value = Union[int, str, list, tuple, set]

# import pprint # for  beautiful printout 
# display is used mostly for jupiter notebook google 
# list  
data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        "abc": [1,2,5],
                        "cde": {"a":1, "b": 2}
                        }

print("Before", data)
data.clear()
# del data
print("After", data)



methods: list[str] = [m for m in dir(data) if "__" not in m]
print(methods)

Before {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}
After {}
['clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']

In [69]:
from  typing import Dict, Union, Optional

import pprint

key = Union[int,str]
Value = Union[int, str, list, tuple, set]

# import pprint # for  beautiful printout 
# display is used mostly for jupiter notebook google 
# list  
data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        "abc": [1,2,5],
                        "cde": {"a":1, "b": 2}
                        }

print("Before", data)
# data.clear()
del data
print("After", data)



methods: list[str] = [m for m in dir(data) if "__" not in m]
print(methods)

Before {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}

NameError: name 'data' is not defined

# POP

In [ ]:
from  typing import Dict, Union, Optional

import pprint

key = Union[int,str]
Value = Union[int, str, list, tuple, set]

# import pprint # for  beautiful printout 
# display is used mostly for jupiter notebook google 
# list  
data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        "abc": [1,2,5],
                        "cde": {"a":1, "b": 2}
                        }

print("Before", data)
# data.clear()

a: str = data.pop("education")
print(a)

print("After", data)



# methods: list[str] = [m for m in dir(data) if "__" not in m]
# print(methods)

Before {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}
BSCS
After {'fname': 'Muhhmad', 'name': 'eale', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}

# popitem

In [ ]:
from  typing import Dict, Union, Optional

import pprint

key = Union[int,str]
Value = Union[int, str, list, tuple, set]

# import pprint # for  beautiful printout 
# display is used mostly for jupiter notebook google 
# list  
data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        "abc": [1,2,5],
                        "cde": {"a":1, "b": 2}
                        }

print("Before", data)
# data.clear()

a: str = data.popitem()
print(a)

print("After", data)



# methods: list[str] = [m for m in dir(data) if "__" not in m]
# print(methods)

Before {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}
('cde', {'a': 1, 'b': 2})
After {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5]}

#  .get

In [ ]:
from  typing import Dict, Union, Optional

import pprint

key = Union[int,str]
Value = Union[int, str, list, tuple, set]

# import pprint # for  beautiful printout 
# display is used mostly for jupiter notebook google 
# list  
data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        "abc": [1,2,5],
                        "cde": {"a":1, "b": 2}
                        }

print("Before", data)
# data.clear()

a: str = data.get("educattrion" , "NOT")
print(a)

print("After", data)



# methods: list[str] = [m for m in dir(data) if "__" not in m]
# print(methods)

Before {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}
NOT
After {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}

# Another Example if its possible

In [ ]:

from  typing import Dict, Union, Optional
import pprint

key = Union[int,str]
Value = Union[int, str, list, tuple, set]

# import pprint # for  beautiful printout 
# display is used mostly for jupiter notebook google 
# list  
data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        "abc": [1,2,5],
                        "cde": {"a":1, "b": 2}
                        }

print("Before", data)
# data.clear()

a: str = data.get("education" , "NOT")
print(a)

print("After", data)



# methods: list[str] = [m for m in dir(data) if "__" not in m]
# print(methods)

Before {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}
BSCS
After {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}

# .setDefault

In [ ]:
from  typing import Dict, Union, Optional

import pprint

key = Union[int,str]
Value = Union[int, str, list, tuple, set]

# import pprint # for  beautiful printout 
# display is used mostly for jupiter notebook google 
# list  
data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        "abc": [1,2,5],
                        "cde": {"a":1, "b": 2}
                        }

print("Before", data)
# data.clear()

a: str = data.setdefault("educationnnnn" )
a: str = data.setdefault("educationnnnn" , "empty value" )
print(a)

print("After", data)



# methods: list[str] = [m for m in dir(data) if "__" not in m]
# print(methods)

Before {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}}
None
After {'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS', 'abc': [1, 2, 5], 'cde': {'a': 1, 'b': 2}, 'educationnnnn': None}

In [ ]:
from  typing import Dict, Union, Optional

import pprint

key = Union[int,str]
Value = Union[int, str, list, tuple, set]


data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        "abc": [1,2,5],
                        "cde": {"a":1, "b": 2}
                        }

data1: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "Qasim", 
                        "Age": "30",
                        "Height": "5:10"
                        }
data.update(data1)
data

{'fname': 'Muhhmad',
 'name': 'Qasim',
 'education': 'BSCS',
 'abc': [1, 2, 5],
 'cde': {'a': 1, 'b': 2},
 'Age': '30',
 'Height': '5:10'}

# Make a table through using dict and pd

In [ ]:
import pandas as pd
from typing import Any

Student_data: Dict[str, list[Any]] = {
"name": ["Waledd", "Qasim", "Jawad"],
"Roll nO":  [1,2,3],
"Education": ['BSCS','BSCS','BSCS']    
} 


df: pd.DataFrame = pd.DataFrame(Student_data)
df

     name  Roll nO Education
0  Waledd        1      BSCS
1   Qasim        2      BSCS
2   Jawad        3      BSCS

In [ ]:
import pandas as pd
from typing import Any

student_data : Dict[str, list[Any]] = {
"Roll nO":  [1,2,3],
"name": ["Waledd", "Qasim", "Jawad"],
"Education": ['BSCS','BSCS','BSCS']    
} 
df : pd.DataFrame = pd.DataFrame(student_data)
df

   Roll nO    name Education
0        1  Waledd      BSCS
1        2   Qasim      BSCS
2        3   Jawad      BSCS

In [ ]:
from typing import Any, Dict

import pandas as pd

student_data: Dict[str, list[Any]] = {
        "Roll nO": [1, 2, 3],
        "name": ["Waledd", "Qasim", "Jawad"],
        "Education": ['BSCS', 'BSCS', 'BSCS']
    }

df: pd.DataFrame = pd.DataFrame(student_data)
df
# This line will print the DataFrame
# except ImportError:
#     # Handle the case where pandas is not installed
# print("Error: pandas is not installed.")

   Roll nO    name Education
0        1  Waledd      BSCS
1        2   Qasim      BSCS
2        3   Jawad      BSCS

In [ ]:
import pandas as pd
from typing import Any

student_data : Dict[str, list[Any]] = {
"Roll nO":  [1,2,3],
"name": ["Waledd", "Qasim", "Jawad"],
"Education": ['BSCS','BSCS','BSCS']    
} 
df : pd.DataFrame = pd.DataFrame(student_data)
df

   Roll nO    name Education
0        1  Waledd      BSCS
1        2   Qasim      BSCS
2        3   Jawad      BSCS

# g

In [ ]:
alien = {'color': 'green', 'points': 5}
print(alien['color'])
print(alien['points'])

green
5

In [ ]:
alien = {'x_position': 0, 'y_position': 25, 'speed': 'medium'}
print(f"Original position: {alien['x_position']}")
# Move the alien to the right.
# Determine how far to move the alien based on its current speed.
if alien['speed'] == 'slow':
    x_increment = 1
elif alien['speed'] == 'medium':
    x_increment = 3
else:
 # This must be a fast alien.
    x_increment =4
# The new position is the old position plus the increment.
alien['x_position'] = alien['x_position'] + x_increment
print(f"New position: {alien['x_position']}")

Original position: 0
New position: 3

In [ ]:
favorite_languages = {
 'jen': 'python',
 'sarah': 'c',
 'edward': 'rust',
 'phil': 'python',
 }
language = favorite_languages['sarah'].title()
print(f"Sarah's favorite language is {language}.")

Sarah's favorite language is C.

In [ ]:
alien_0 = {'color': 'green', 'speed': 'slow'}
point_value = alien_0.get('points', 'No point value assigned.')
print(point_value)

No point value assigned.

In [ ]:
alien_0 = {'color': 'green', 'speed': 'slow'}
point_value = alien_0.get('color', 'No point value assigned.')
print(point_value)

green

In [ ]:
alien_0 = {'color': 'green', 'speed': 'slow'}
print(alien_0['points'])

KeyError: 'points'

In [ ]:
user_0 = {
 'username': 'efermi',
 'first': 'enrico',
 'last': 'fermi',
 }
for key, value in user_0.items():
 print(f"\nKey: {key}")
 print(f"Value: {value}")

Key: username
Value: efermi

Key: first
Value: enrico

Key: last
Value: fermi

In [ ]:
favorite_languages = {
'jen': 'python',
 'sarah': 'c',
 'edward': 'rust',
 'phil': 'python',
  'sarah': 'rkust',
 }
friends = ['phil', 'sarah']
for name in favorite_languages.keys():
    print(f"Hi {name.title()}.")
    if name in friends:
       language = favorite_languages[name].title()
       print(f"\t{name.title()}, I see you love {language}!")

Hi Jen.
Hi Sarah.
	Sarah, I see you love Rkust!
Hi Edward.
Hi Phil.
	Phil, I see you love Python!

# Sorted

In [ ]:
favorite_languages = {
 'jen': 'python',
 'sarah': 'c',
 'edward': 'rust',
 'phil': 'python',
 }
for name in sorted(favorite_languages.keys()):
 print(f"{name.title()}, thank you for taking the poll.")

Edward, thank you for taking the poll.
Jen, thank you for taking the poll.
Phil, thank you for taking the poll.
Sarah, thank you for taking the poll.

In [ ]:
alien_0 = {'color': 'green', 'points': 5}
alien_1 = {'color': 'yellow', 'points': 10}
alien_2 = {'color': 'red', 'points': 15}

aliens = [alien_0, alien_1, alien_2]
for alien in aliens:
 print(alien)

{'color': 'green', 'points': 5}
{'color': 'yellow', 'points': 10}
{'color': 'red', 'points': 15}

In [ ]:
from typing import Key
alien_0: list[Key ,Value] = {'color': 'green', 'points': 5}
alien_1: list[Key,Value] = {'color': 'yellow', 'points': 10}
alien_2: list[Key,Value] = {'color': 'red', 'points': 15}

aliens: list[Dict[str, str]] = [alien_0, alien_1, alien_2]
for alien in aliens:
 print(alien)

ImportError: cannot import name 'Key' from 'typing' (c:\Users\Waleed Khokhar\anaconda3\envs\pythooon\Lib\typing.py)

In [71]:
aliens: list[Dict[str, str]] = []
# Make 30 green aliens.
print(aliens)
for alien_number in range(30):
    new_alien = {'color': 'green', 'points': 5, 'speed': 'slow'}
    aliens.append(new_alien)
# # Show the first 5 aliens.
for alien in aliens[:5]:
    print(alien)
#      print("...")
# # Show how many aliens have been created.
# print(f"Total number of aliens: {len(aliens)}")

[]
{'color': 'green', 'points': 5, 'speed': 'slow'}
{'color': 'green', 'points': 5, 'speed': 'slow'}
{'color': 'green', 'points': 5, 'speed': 'slow'}
{'color': 'green', 'points': 5, 'speed': 'slow'}
{'color': 'green', 'points': 5, 'speed': 'slow'}

In [78]:
for alien in aliens[:3]:
 if alien['color'] == 'green':
     alien['color'] = 'yellow'
     alien['speed'] = 'medium'
     alien['points'] = 10
aliens

[{'color': 'yellow', 'points': 10, 'speed': 'medium'},
 {'color': 'yellow', 'points': 10, 'speed': 'medium'},
 {'color': 'yellow', 'points': 10, 'speed': 'medium'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'},
 {'color': 'green', 'points': 5, 'speed': 'slow'}]

In [7]:

key = Union[int,str]
Value = Union[int, str, list, tuple, set]

data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        "abc": [1,2,5],
                        "cde": {"a":1, "b": 2}
                        }
print(data)
print(type(data))

NameError: name 'Union' is not defined

# JSON

In [9]:
from  typing import Dict, Union, Optional

import pprint

key = Union[int,str]
Value = Union[int, str, list, tuple, set]


data: Dict[key, Value] = {
    "fname": "Muhhmad", 
                        "name": "eale", 
                        "education": "BSCS",
                        }
print(data)
print(type(data))

{'fname': 'Muhhmad', 'name': 'eale', 'education': 'BSCS'}
<class 'dict'>

In [11]:
import json

data1 = json.dumps(data, indent=2)

print(type(str(data1)))
print(data1)

<class 'str'>
{
  "fname": "Muhhmad",
  "name": "eale",
  "education": "BSCS"
}